"""add category to requirement

Revision ID: 42c834766431
Revises: 980da6c89460
Create Date: 2026-03-28 07:08:17.522786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c834766431'
down_revision = '980da6c89460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_timers')
    with op.batch_alter_table('incentives', schema=None) as batch_op:
        batch_op.drop_column('amount_detail')

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('incentives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_detail', sa.VARCHAR(length=200), nullable=True))

    op.create_table('activity_timers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('activity', sa.VARCHAR(length=30), nullable=False),
    sa.Column('label', sa.VARCHAR(length=50), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('minutes', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
