"""add amount_detail to incentive

Revision ID: 980da6c89460
Revises: 0c71dc39caa1
Create Date: 2026-03-27 08:24:20.059134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980da6c89460'
down_revision = '0c71dc39caa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_timers')
    op.drop_table('standup_records')
    with op.batch_alter_table('aars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_aar_title'))

    with op.batch_alter_table('incentives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_detail', sa.String(length=200), nullable=True))

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_meeting_title'))

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_req_title'))

    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_risk_title'))

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_todo_title'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_name'), ['name'], unique=False)

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_todo_title'), ['title'], unique=False)

    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_risk_title'), ['title'], unique=False)

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_req_title'), ['title'], unique=False)

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_meeting_title'), ['title'], unique=False)

    with op.batch_alter_table('incentives', schema=None) as batch_op:
        batch_op.drop_column('amount_detail')

    with op.batch_alter_table('aars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_aar_title'), ['title'], unique=False)

    op.create_table('standup_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('yesterday_done', sa.TEXT(), nullable=True),
    sa.Column('today_plan', sa.TEXT(), nullable=True),
    sa.Column('blocker', sa.TEXT(), nullable=True),
    sa.Column('has_blocker', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name=op.f('uq_standup_user_date'))
    )
    op.create_table('activity_timers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('activity', sa.VARCHAR(length=30), nullable=False),
    sa.Column('label', sa.VARCHAR(length=50), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('minutes', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
